spring.application.name=hms

spring.security.user.name=admin
spring.security.user.password=admin

spring.security.oauth2.client.registration.github-id=
spring.security.oauth2.client.registration.github-secret=
spring.security.oauth2.client.registration.github-scope=read:user,user:email